paths:
  kproto_model_path: "datasets/kproto_model.joblib"
  final_result_path: "datasets/final_result.csv"
  final_result_with_cluster_path: 'datasets/final_result_with_clusters.csv'
  json_path: "datasets/user_clothes.json"


